<?php

return [
    'brand_tagline' => 'Entradas de futbol con checkout rapido y gestion profesional.',
    'nav' => ['home' => 'Inicio', 'events' => 'Eventos', 'stadiums' => 'Estadios', 'dashboard' => 'Mis entradas', 'orders' => 'Pedidos', 'admin' => 'Admin', 'reports' => 'Reportes', 'login' => 'Acceder', 'register' => 'Crear cuenta', 'logout' => 'Salir', 'teams' => 'Equipos', 'competitions' => 'Competiciones', 'sectors' => 'Sectores', 'payments' => 'Pagos', 'tickets' => 'Tickets'],
    'hero' => ['badge' => 'Ticketing premium', 'title' => 'Compra entradas de futbol con la energia del partido antes de llegar al estadio.', 'description' => 'SERKO conecta aficionados, clubes y recintos en una experiencia de venta moderna, rapida y segura.', 'cta_primary' => 'Explorar partidos', 'cta_secondary' => 'Ver estadios', 'card_label' => 'Matchday radar'],
    'stats' => ['events' => 'Eventos disponibles', 'stadiums' => 'Estadios activos'],
    'dashboard' => ['kicker' => 'Area privada', 'title' => 'Tus entradas', 'subtitle' => 'Accede a tus QR, revisa pedidos y prepara tus proximos partidos.', 'ticket' => 'Entrada', 'tickets' => 'entradas', 'orders' => 'Pedidos', 'upcoming' => 'Proximos eventos', 'recent_orders' => 'Pedidos recientes', 'latest_tickets' => 'Ultimas entradas', 'next_match' => 'Siguiente partido', 'empty' => 'Todavia no has comprado entradas.', 'view_orders' => 'Ver historial completo', 'browse_events' => 'Comprar entradas'],
    'events' => ['title' => 'Eventos destacados', 'subtitle' => 'Encuentra futbol en vivo y selecciona tu sitio.', 'search' => 'Buscar equipo o estadio...', 'view' => 'Ver detalles', 'date' => 'Fecha', 'stadium' => 'Estadio', 'available' => 'Asientos disponibles', 'buy_box_title' => 'Compra en minutos', 'buy_box_description' => 'Selecciona tus asientos y paga con PayPal.', 'buy_now' => 'Ir al checkout', 'login_to_buy' => 'Inicia sesion para comprar', 'description' => 'Descripcion', 'competition' => 'Competicion', 'created' => 'Evento creado correctamente.', 'updated' => 'Evento actualizado correctamente.', 'deleted' => 'Evento eliminado correctamente.'],
    'stadiums' => ['title' => 'Estadios', 'subtitle' => 'Explora recintos y su distribucion.', 'view' => 'Ver estadio', 'seats' => 'plazas', 'sectors_title' => 'Sectores', 'upcoming_events' => 'Proximos eventos', 'name' => 'Nombre', 'city' => 'Ciudad', 'capacity' => 'Capacidad', 'created' => 'Estadio creado correctamente.', 'updated' => 'Estadio actualizado correctamente.', 'deleted' => 'Estadio eliminado correctamente.'],
    'orders' => ['checkout_title' => 'Checkout', 'payment_title' => 'Pago PayPal', 'payment_help' => 'Confirma primero el pago y SERKO validara los asientos disponibles antes de emitir tus entradas.', 'selected' => 'Seleccionados', 'total' => 'Total', 'complete' => 'Confirmar compra', 'completed' => 'Compra completada', 'summary' => 'Tu pedido se ha registrado por un total de :total EUR.', 'order' => 'Pedido', 'history_kicker' => 'Historial', 'history_title' => 'Tus pedidos SERKO', 'history_subtitle' => 'Consulta compras, pagos y entradas generadas con QR.', 'empty' => 'Aun no tienes pedidos. Cuando compres entradas apareceran aqui.', 'pitch' => 'Campo', 'available' => 'Disponible', 'reserved' => 'Reservado', 'sold' => 'Vendido'],
    'auth' => ['login' => 'Acceder', 'register' => 'Registrarse', 'name' => 'Nombre', 'email' => 'Email', 'password' => 'Contrasena', 'password_confirmation' => 'Confirmar contrasena', 'remember' => 'Recordarme'],
    'admin' => ['hub_kicker' => 'Backoffice premium', 'hub_title' => 'Centro de mando SERKO', 'hub_subtitle' => 'Gestiona inventario, ventas, reportes y modulos ampliados desde una consola visual.', 'events_title' => 'Gestion de eventos', 'events_subtitle' => 'Controla el calendario, los precios y la disponibilidad.', 'new_event' => 'Nuevo evento', 'edit_event' => 'Editar evento', 'stadiums_title' => 'Gestion de estadios', 'stadiums_subtitle' => 'Actualiza recintos e imagenes.', 'new_stadium' => 'Nuevo estadio', 'edit_stadium' => 'Editar estadio', 'save' => 'Guardar cambios', 'drag_drop' => 'Arrastra una imagen o pulsa para subirla', 'reports_kicker' => 'Operaciones', 'reports_title' => 'Reportes y exportaciones', 'reports_subtitle' => 'Controla ingresos, ventas y calendario exportable para direccion.', 'paid_orders' => 'Pedidos pagados', 'revenue' => 'Ingresos', 'events_metric' => 'Eventos', 'sold_tickets' => 'Tickets vendidos', 'exports_title' => 'Exportaciones Excel', 'exports_subtitle' => 'Descarga ventas y eventos con datos listos para presentar.', 'export_sales' => 'Exportar ventas', 'export_events' => 'Exportar eventos'],
    'mail' => ['purchase_subject' => 'Confirmacion de compra SERKO #:order', 'reminder_subject' => 'Recordatorio de tu evento SERKO', 'purchase_heading' => 'Compra confirmada', 'purchase_intro' => 'Tu pedido #:order ya esta confirmado.', 'reminder_heading' => 'Tu partido empieza pronto', 'payment_receipt_subject' => 'Recibo de pago SERKO #:payment', 'payment_receipt_heading' => 'Pago confirmado', 'admin_report_subject' => 'Reporte SERKO :type', 'admin_report_heading' => 'Reporte exportado', 'seat_reserved_subject' => 'Asiento reservado en SERKO', 'seat_reserved_heading' => 'Reserva registrada'],
    'validation' => ['seat_unavailable' => 'Uno o varios asientos ya no estan disponibles.'],
];
